CREATE TABLE IF NOT EXISTS app.SHOE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    -- DOUBLE HAS EIGHT BITS FOR PRECISION WHEREAS
    -- FLOAT HAS FOUR BITS AND WE DO NOT REQUIRE
    -- THE EXTRA PRECISION
    SIZE FLOAT NOT NULL,
    BRAND VARCHAR(255) NOT NULL
);